
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpascoirpldvfcatkyto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYXNjb2lycGxkdmZjYXRreXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTU5MjEsImV4cCI6MjA2MjAzMTkyMX0.gazFY6Y_40m9A2oQFOg8TJNqCQCmf0zaFis_HrG2OQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Function to check if the connection to Supabase is active
export const isSupabaseConnected = async (): Promise<boolean> => {
  try {
    // Check if the products bucket exists
    const { data, error } = await supabase.storage.getBucket('products');
    if (error) {
      if (error.message.includes("Bucket not found")) {
        console.error("Products bucket not found. Please initialize the storage bucket.");
      }
      return false;
    }
    return true;
  } catch (error) {
    console.error("Error checking Supabase connection:", error);
    return false;
  }
};

// Helper function to log and display database errors
export const handleSupabaseError = (error: any, toast?: any) => {
  console.error("Supabase error:", error);
  
  // Prepare a user-friendly message
  let errorMessage = "Une erreur s'est produite. Veuillez réessayer.";
  
  if (error?.message) {
    // Handle specific storage errors
    if (error.message.includes("Bucket not found")) {
      errorMessage = "Erreur: Le bucket de stockage 'products' n'existe pas. Veuillez contacter l'administrateur.";
    } else if (error.message.includes("storage")) {
      errorMessage = "Erreur de stockage: Impossible de télécharger l'image. Veuillez réessayer.";
    } else {
      errorMessage = `Erreur: ${error.message}`;
    }
  }
  
  // If toast is provided, show the error message
  if (toast) {
    toast({
      title: "Erreur",
      description: errorMessage,
      variant: "destructive"
    });
  }
  
  return errorMessage;
};

// Initialize Supabase with required tables and functions
export const initializeSupabase = async () => {
  try {
    const connected = await isSupabaseConnected();
    if (!connected) {
      console.error("Failed to connect to Supabase");
      return false;
    }
    
    console.log("Successfully connected to Supabase");
    
    // You could add additional initialization here if needed
    // For example, checking if required tables exist
    
    return true;
  } catch (error) {
    console.error("Error initializing Supabase:", error);
    return false;
  }
};
