
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpascoirpldvfcatkyto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYXNjb2lycGxkdmZjYXRreXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTU5MjEsImV4cCI6MjA2MjAzMTkyMX0.gazFY6Y_40m9A2oQFOg8TJNqCQCmf0zaFis_HrG2OQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Function to check if the connection to Supabase is active
export const isSupabaseConnected = async (): Promise<boolean> => {
  try {
    const { error } = await supabase.from('products').select('count').limit(1);
    
    if (error) {
      console.error("Erreur de connexion à Supabase:", error.message);
      return false;
    }
    
    return true;
  } catch (error) {
    console.error("Erreur lors de la vérification de la connexion à Supabase:", error);
    return false;
  }
};

// Helper function to log and display database errors
export const handleSupabaseError = (error: any, toast?: any) => {
  console.error("Supabase error:", error);
  
  // Prepare a user-friendly message
  let errorMessage = "Une erreur s'est produite. Veuillez réessayer.";
  
  if (error?.message) {
    // Handle specific storage errors
    if (error.message.includes("Bucket not found")) {
      errorMessage = "Erreur: Le bucket de stockage n'existe pas. Veuillez contacter l'administrateur.";
    } else if (error.message.includes("storage")) {
      errorMessage = "Erreur de stockage: Impossible de télécharger l'image. Veuillez réessayer.";
    } else {
      errorMessage = `Erreur: ${error.message}`;
    }
  }
  
  // If toast is provided, show the error message
  if (toast) {
    toast({
      title: "Erreur",
      description: errorMessage,
      variant: "destructive"
    });
  }
  
  return errorMessage;
};

// Initialize Supabase with required tables and functions
export const initializeSupabase = async () => {
  try {
    const connected = await isSupabaseConnected();
    if (!connected) {
      console.error("Impossible de se connecter à Supabase");
      return false;
    }
    
    console.log("Connexion à Supabase établie avec succès");
    return true;
  } catch (error) {
    console.error("Erreur d'initialisation de Supabase:", error);
    return false;
  }
};
