
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from '@/hooks/use-toast';

const SUPABASE_URL = "https://kpascoirpldvfcatkyto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYXNjb2lycGxkdmZjYXRreXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTU5MjEsImV4cCI6MjA2MjAzMTkyMX0.gazFY6Y_40m9A2oQFOg8TJNqCQCmf0zaFis_HrG2OQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type for Store data
export interface StoreData {
  id?: string; // Maintenant optionnel lors de la création
  name: string;
  products: string[];
  media_url?: string;
  media_type?: "image" | "video";
  show_media?: boolean;
  description?: string;
  address?: string;
  contact?: string;
  created_at?: string;
  updated_at?: string;
}

// Function to check if Supabase is connected
export const isSupabaseConnected = async (): Promise<boolean> => {
  try {
    const { data, error } = await supabase.from('whatsapp_redirects').select('count');
    return !error;
  } catch (error) {
    console.error("Erreur lors de la vérification de connexion à Supabase:", error);
    return false;
  }
};

// Helper function to handle Supabase errors in a consistent way
export const handleSupabaseError = (error: any, toastFunction?: any) => {
  console.error("Supabase error:", error);
  
  const errorMessage = error.message || "Une erreur est survenue";
  
  if (toastFunction) {
    toastFunction({
      title: "Erreur",
      description: errorMessage,
      variant: "destructive"
    });
  }
  
  return errorMessage;
};

// Store CRUD functions
export const createStore = async (storeData: StoreData): Promise<StoreData> => {
  const { data, error } = await supabase
    .from('stores')
    .insert(storeData)
    .select()
    .single();
  
  if (error) {
    throw error;
  }
  
  return data as StoreData;
};

export const updateStore = async (id: string, storeData: StoreData): Promise<StoreData> => {
  const { data, error } = await supabase
    .from('stores')
    .update(storeData)
    .eq('id', id)
    .select()
    .single();
  
  if (error) {
    throw error;
  }
  
  return data as StoreData;
};

export const deleteStore = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('stores')
    .delete()
    .eq('id', id);
  
  if (error) {
    throw error;
  }
};

export const fetchStores = async (): Promise<StoreData[]> => {
  const { data, error } = await supabase
    .from('stores')
    .select('*')
    .order('created_at', { ascending: false });
  
  if (error) {
    throw error;
  }
  
  return data as StoreData[];
};

export const fetchStoreById = async (id: string): Promise<StoreData | null> => {
  const { data, error } = await supabase
    .from('stores')
    .select('*')
    .eq('id', id)
    .maybeSingle();
  
  if (error) {
    throw error;
  }
  
  return data as StoreData;
};

// Autres fonctions utilitaires pourraient être ajoutées ici au besoin

